<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class LandingPagesSeeder extends Seeder
{
    public function run(): void
    {
        $records = [
            ['id' => 1, 'theme' => 'default', 'name' => 'Hero Section', 'code' => 'hero', 'data' => '{\"qr_text\":\"Get the xanzo app\",\"qr_image\":\"global\\/uploadsglobal\\/images\\/nsrSYefZQSYuG3oVd8Vr.png\",\"hero_image\":\"global\\/uploadsglobal\\/images\\/Oa5Ps4o1zbCPq2th1s4W.png\",\"hero_title\":\"Pay Your Way. On Your Terms\",\"background_image\":\"global\\/uploadsglobal\\/images\\/HcBbBJAtKJhXFz2t0oWo.png\",\"hero_description\":\"Get what you love today and split the cost into simple, predictable installments - no surprises, no stress.\"}', 'status' => 1, 'created_at' => '2026-04-25 03:55:53', 'updated_at' => '2026-04-25 06:48:47', 'short' => 1, 'locale' => 'en'],
            ['id' => 2, 'theme' => 'default', 'name' => 'How It Works Section', 'code' => 'how-it-works', 'data' => '{\"title\":\"How It Works\",\"right_image\":\"global\\/uploadsglobal\\/images\\/B4khofUCO97U8Sv9ca7Q.png\",\"background_image\":\"global\\/uploads\\/global\\/images\\/8sFLu8zFrnZ9rGprPPqV.png\"}', 'status' => 1, 'created_at' => '2026-04-25 03:55:53', 'updated_at' => '2026-05-11 09:13:18', 'short' => 2, 'locale' => 'en'],
            ['id' => 3, 'theme' => 'default', 'name' => 'Stats Section', 'code' => 'stats', 'data' => '{\"background_image\":\"global\\/uploads\\/global\\/images\\/0lxwh8lAA2xJXJTwbQpU.png\"}', 'status' => 1, 'created_at' => '2026-04-25 03:55:53', 'updated_at' => '2026-04-26 06:45:53', 'short' => 3, 'locale' => 'en'],
            ['id' => 4, 'theme' => 'default', 'name' => 'Why Choose Us Section', 'code' => 'why-choose-us', 'data' => '{\"title\": \"Why Choose Us\"}', 'status' => 1, 'created_at' => '2026-04-25 03:55:53', 'updated_at' => '2026-04-25 03:55:53', 'short' => 4, 'locale' => 'en'],
            ['id' => 5, 'theme' => 'default', 'name' => 'About Us Section', 'code' => 'about-us', 'data' => '{\"title\":\"Redefining How People Pay\",\"left_image\":\"global\\/uploadsglobal\\/images\\/ApR7NBBSBBGQlN7zKZZC.png\",\"description\":\"We help shoppers buy what they love today and pay over time - without interest, hidden fees, or complicated approvals. Our Buy Now, Pay Later platform makes payments simple, transparent, and accessible for everyone. Founded to remove financial friction, we partner with merchants to create smoother checkout experiences and smarter spending for customers.\",\"background_image\":\"global\\/uploads\\/global\\/images\\/y0b6sdIujfq820tRi4Rb.png\"}', 'status' => 1, 'created_at' => '2026-04-25 03:55:53', 'updated_at' => '2026-04-25 08:09:25', 'short' => 5, 'locale' => 'en'],
            ['id' => 6, 'theme' => 'default', 'name' => 'Pay In 4 Section', 'code' => 'pay-in-4', 'data' => '{\"title\":\"4 Payments. Zero Stress.\",\"bullet_one\":\"No upfront stress\",\"bullet_two\":\"Auto payments enabled\",\"bullet_four\":\"Track payments anytime\",\"description\":\"Pay over time anywhere VISA is accepted with your Xanzo Card.\",\"right_image\":\"global\\/uploadsglobal\\/images\\/buzIHtyAL5PiAHIiA4sZ.png\",\"bullet_three\":\"Flexible due dates\"}', 'status' => 1, 'created_at' => '2026-04-25 03:55:53', 'updated_at' => '2026-04-25 04:16:23', 'short' => 6, 'locale' => 'en'],
            ['id' => 7, 'theme' => 'default', 'name' => 'FAQ Section', 'code' => 'faq', 'data' => '{\"title\":\"Frequently Asked Questions\",\"background_image\":\"global\\/uploadsglobal\\/images\\/AAnhS8IDF4irgxjTryPH.png\"}', 'status' => 1, 'created_at' => '2026-04-25 03:55:53', 'updated_at' => '2026-04-25 04:17:18', 'short' => 7, 'locale' => 'en'],
            ['id' => 8, 'theme' => 'default', 'name' => 'Testimonials Section', 'code' => 'testimonials', 'data' => '{\"testimonial_title\": \"Trusted by Thousands of Smart Shoppers\"}', 'status' => 1, 'created_at' => '2026-04-25 03:55:53', 'updated_at' => '2026-04-25 03:55:53', 'short' => 8, 'locale' => 'en'],
            ['id' => 9, 'theme' => 'default', 'name' => 'App Link Section', 'code' => 'app-link', 'data' => '{\"title\":\"Smarter Shopping Starts in Your Pocket\",\"description\":\"Split payments, stay organized, and never miss a due date again\",\"right_image\":\"global\\/uploadsglobal\\/images\\/MgCYyqvfieNzOJvUal9w.png\",\"app_store_url\":\"\\/\",\"app_store_icon\":\"global\\/uploadsglobal\\/images\\/9BCPmoNfOVIGtzNchhUh.png\",\"play_store_url\":\"\\/\",\"play_store_icon\":\"global\\/uploadsglobal\\/images\\/iuiFD5cPLQZVgAAElFfB.png\",\"background_image\":\"global\\/uploadsglobal\\/images\\/EtwA6ntKMYptuWUmcGrT.png\"}', 'status' => 1, 'created_at' => '2026-04-25 03:55:53', 'updated_at' => '2026-04-25 04:41:22', 'short' => 9, 'locale' => 'en'],
            ['id' => 10, 'theme' => 'default', 'name' => 'Hero Section', 'code' => 'hero', 'data' => '{\"qr_text\": \"Get the xanzo app\", \"qr_image\": \"assets/landing-page/hero-section/QR-Code.png\", \"hero_image\": \"assets/landing-page/hero-section/hero-img.png\", \"hero_title\": \"Pay Your Way. On Your Terms\", \"background_image\": \"assets/landing-page/hero-section/hero-bg.png\", \"hero_description\": \"Get what you love today and split the cost into simple, predictable installments - no surprises, no stress.\"}', 'status' => 1, 'created_at' => '2026-04-25 03:55:53', 'updated_at' => '2026-04-25 06:48:47', 'short' => 1, 'locale' => 'ar'],
            ['id' => 11, 'theme' => 'default', 'name' => 'How It Works Section', 'code' => 'how-it-works', 'data' => '{\"title\": \"How It Works\", \"right_image\": \"assets/landing-page/how-its-works/how-it-works.png\", \"background_image\": \"assets/landing-page/how-its-works/how-its-works-bg.png\"}', 'status' => 1, 'created_at' => '2026-04-25 03:55:53', 'updated_at' => '2026-05-11 09:13:18', 'short' => 2, 'locale' => 'ar'],
            ['id' => 12, 'theme' => 'default', 'name' => 'Stats Section', 'code' => 'stats', 'data' => '{\"background_image\": \"assets/landing-page/stats/stats-bg.png\"}', 'status' => 1, 'created_at' => '2026-04-25 03:55:53', 'updated_at' => '2026-04-26 06:45:53', 'short' => 3, 'locale' => 'ar'],
            ['id' => 13, 'theme' => 'default', 'name' => 'Why Choose Us Section', 'code' => 'why-choose-us', 'data' => '{\"title\": \"Why Choose Us\"}', 'status' => 1, 'created_at' => '2026-04-25 03:55:53', 'updated_at' => '2026-04-25 03:55:53', 'short' => 4, 'locale' => 'ar'],
            ['id' => 14, 'theme' => 'default', 'name' => 'About Us Section', 'code' => 'about-us', 'data' => '{\"title\": \"Redefining How People Pay\", \"left_image\": \"assets/landing-page/about-us/about-us.png\", \"description\": \"We help shoppers buy what they love today and pay over time - without interest, hidden fees, or complicated approvals. Our Buy Now, Pay Later platform makes payments simple, transparent, and accessible for everyone. Founded to remove financial friction, we partner with merchants to create smoother checkout experiences and smarter spending for customers.\", \"background_image\": \"assets/landing-page/about-us/about-us-bg.png\"}', 'status' => 1, 'created_at' => '2026-04-25 03:55:53', 'updated_at' => '2026-04-25 08:09:25', 'short' => 5, 'locale' => 'ar'],
            ['id' => 15, 'theme' => 'default', 'name' => 'Pay In 4 Section', 'code' => 'pay-in-4', 'data' => '{\"title\": \"4 Payments. Zero Stress.\", \"bullet_one\": \"No upfront stress\", \"bullet_two\": \"Auto payments enabled\", \"bullet_four\": \"Track payments anytime\", \"description\": \"Pay over time anywhere VISA is accepted with your Xanzo Card.\", \"right_image\": \"assets/landing-page/how-to-do/how-to-do.png\", \"bullet_three\": \"Flexible due dates\"}', 'status' => 1, 'created_at' => '2026-04-25 03:55:53', 'updated_at' => '2026-04-25 04:16:23', 'short' => 6, 'locale' => 'ar'],
            ['id' => 16, 'theme' => 'default', 'name' => 'FAQ Section', 'code' => 'faq', 'data' => '{\"title\": \"Frequently Asked Questions\", \"background_image\": \"assets/landing-page/faq/faq-bg.png\"}', 'status' => 1, 'created_at' => '2026-04-25 03:55:53', 'updated_at' => '2026-04-25 04:17:18', 'short' => 7, 'locale' => 'ar'],
            ['id' => 17, 'theme' => 'default', 'name' => 'Testimonials Section', 'code' => 'testimonials', 'data' => '{\"testimonial_title\": \"Trusted by Thousands of Smart Shoppers\"}', 'status' => 1, 'created_at' => '2026-04-25 03:55:53', 'updated_at' => '2026-04-25 03:55:53', 'short' => 8, 'locale' => 'ar'],
            ['id' => 18, 'theme' => 'default', 'name' => 'App Link Section', 'code' => 'app-link', 'data' => '{\"title\": \"Smarter Shopping Starts in Your Pocket\", \"description\": \"Split payments, stay organized, and never miss a due date again\", \"right_image\": \"assets/landing-page/app-link/app-img.png\", \"app_store_url\": \"/\", \"app_store_icon\": \"assets/landing-page/app-link/app-store-icon.png\", \"play_store_url\": \"/\", \"play_store_icon\": \"assets/landing-page/app-link/play-store-icon.png\", \"background_image\": \"assets/landing-page/app-link/app-link-bg.png\"}', 'status' => 1, 'created_at' => '2026-04-25 03:55:53', 'updated_at' => '2026-04-25 04:41:22', 'short' => 9, 'locale' => 'ar'],
            ['id' => 25, 'theme' => 'default', 'name' => 'Footer Section', 'code' => 'footer', 'data' => '{\"about_us\": \"Xanzo helps shoppers split payments with clarity, flexibility, and zero hidden stress.\", \"left_img\": \"assets/landing-page/footer/payment-methods.png\", \"copyright_text\": \"Copyright 2026 Xanzo. All rights reserved.\", \"contact_phone_number\": \"+1 000 000 0000\", \"contact_email_address\": \"support@xanzo.com\", \"footer_widget_1_title\": \"Company\", \"footer_widget_2_title\": \"Resources\", \"footer_widget_3_title\": \"Support\"}', 'status' => 1, 'created_at' => '2026-04-25 04:45:47', 'updated_at' => '2026-04-25 04:45:47', 'short' => 10, 'locale' => 'en'],
            ['id' => 26, 'theme' => 'default', 'name' => 'Footer Section', 'code' => 'footer', 'data' => '{\"about_us\": \"Xanzo helps shoppers split payments with clarity, flexibility, and zero hidden stress.\", \"left_img\": \"assets/landing-page/footer/payment-methods.png\", \"copyright_text\": \"Copyright 2026 Xanzo. All rights reserved.\", \"contact_phone_number\": \"+1 000 000 0000\", \"contact_email_address\": \"support@xanzo.com\", \"footer_widget_1_title\": \"Company\", \"footer_widget_2_title\": \"Resources\", \"footer_widget_3_title\": \"Support\"}', 'status' => 1, 'created_at' => '2026-04-25 04:45:47', 'updated_at' => '2026-04-25 04:45:47', 'short' => 10, 'locale' => 'ar'],
        ];

        foreach ($records as $record) {
            DB::table('landing_pages')->updateOrInsert(
                ['id' => $record['id']],
                $record
            );
        }
    }
}
