<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class LandingContentsSeeder extends Seeder
{
    public function run(): void
    {
        $records = [
            ['id' => 1, 'theme' => 'default', 'icon' => 'global/uploadsglobal/images/EkmXhBOGcqdQul0iTQfx.png', 'title' => 'Choose BNPL at Checkout', 'description' => 'Select Pay with FlexPay when shopping.', 'photo' => null, 'type' => 'how-it-works', 'created_at' => '2026-04-25 03:55:54', 'updated_at' => '2026-04-25 04:05:23', 'locale_id' => 1, 'locale' => 'en'],
            ['id' => 2, 'theme' => 'default', 'icon' => 'global/uploadsglobal/images/1CEkcSu6M2ruWfgQ30NQ.png', 'title' => 'Get Instant Approval', 'description' => 'No credit score impact. Approval in seconds.', 'photo' => null, 'type' => 'how-it-works', 'created_at' => '2026-04-25 03:55:54', 'updated_at' => '2026-04-25 04:05:36', 'locale_id' => 2, 'locale' => 'en'],
            ['id' => 3, 'theme' => 'default', 'icon' => 'global/uploadsglobal/images/FYA0dbJq2oXm3J25GXNM.png', 'title' => 'Pay in Installments', 'description' => 'Split into 4 or monthly payments - interest free.', 'photo' => null, 'type' => 'how-it-works', 'created_at' => '2026-04-25 03:55:54', 'updated_at' => '2026-04-25 04:05:49', 'locale_id' => 3, 'locale' => 'en'],
            ['id' => 4, 'theme' => 'default', 'icon' => 'global/uploadsglobal/images/E9mUe3rUIy2PZn6GqaZQ.png', 'title' => '$25M+', 'description' => 'Transactions Processed', 'photo' => null, 'type' => 'stats', 'created_at' => '2026-04-25 03:55:54', 'updated_at' => '2026-04-25 04:11:27', 'locale_id' => 4, 'locale' => 'en'],
            ['id' => 5, 'theme' => 'default', 'icon' => 'global/uploadsglobal/images/WeKHXX7Hh4h7RVW6Cs9f.png', 'title' => '50,000+', 'description' => 'Active Shoppers', 'photo' => null, 'type' => 'stats', 'created_at' => '2026-04-25 03:55:54', 'updated_at' => '2026-04-25 04:11:34', 'locale_id' => 5, 'locale' => 'en'],
            ['id' => 6, 'theme' => 'default', 'icon' => 'global/uploadsglobal/images/gaNXighk5km6uBwgM9lJ.png', 'title' => '1200+', 'description' => 'Partner Stores', 'photo' => null, 'type' => 'stats', 'created_at' => '2026-04-25 03:55:54', 'updated_at' => '2026-04-25 04:11:40', 'locale_id' => 6, 'locale' => 'en'],
            ['id' => 7, 'theme' => 'default', 'icon' => 'global/uploadsglobal/images/yqOEbmjpFMd5ZKoKm5vX.png', 'title' => '98%', 'description' => 'Approval Rate', 'photo' => null, 'type' => 'stats', 'created_at' => '2026-04-25 03:55:54', 'updated_at' => '2026-04-25 04:11:47', 'locale_id' => 7, 'locale' => 'en'],
            ['id' => 8, 'theme' => 'default', 'icon' => 'global/uploadsglobal/images/OcvPpL5xydRxocfuNouL.png', 'title' => 'Instant Approval', 'description' => 'No paperwork. No waiting.', 'photo' => null, 'type' => 'why-choose-us', 'created_at' => '2026-04-25 03:55:54', 'updated_at' => '2026-04-25 04:14:55', 'locale_id' => 8, 'locale' => 'en'],
            ['id' => 9, 'theme' => 'default', 'icon' => 'global/uploadsglobal/images/7J48Kt1CASu4zl8J8M6h.png', 'title' => 'Bank-Level Security', 'description' => 'Your data is fully encrypted.', 'photo' => null, 'type' => 'why-choose-us', 'created_at' => '2026-04-25 03:55:54', 'updated_at' => '2026-04-25 04:15:04', 'locale_id' => 9, 'locale' => 'en'],
            ['id' => 10, 'theme' => 'default', 'icon' => 'global/uploadsglobal/images/2UB6u4fqdWryAz8AUzon.png', 'title' => 'Zero Hidden Fees', 'description' => 'What you see is what you pay.', 'photo' => null, 'type' => 'why-choose-us', 'created_at' => '2026-04-25 03:55:54', 'updated_at' => '2026-04-25 04:15:13', 'locale_id' => 10, 'locale' => 'en'],
            ['id' => 11, 'theme' => 'default', 'icon' => 'global/uploadsglobal/images/gprFO4xIZI4PDRUQCOgT.png', 'title' => 'Manage in One App', 'description' => 'Track payments anytime.', 'photo' => null, 'type' => 'why-choose-us', 'created_at' => '2026-04-25 03:55:54', 'updated_at' => '2026-04-25 04:15:25', 'locale_id' => 11, 'locale' => 'en'],
            ['id' => 12, 'theme' => 'default', 'icon' => null, 'title' => 'Transparency', 'description' => 'No hidden charges. Ever.', 'photo' => null, 'type' => 'about-us', 'created_at' => '2026-04-25 03:55:54', 'updated_at' => '2026-04-25 03:55:54', 'locale_id' => 12, 'locale' => 'en'],
            ['id' => 13, 'theme' => 'default', 'icon' => null, 'title' => 'Simplicity', 'description' => 'Fast onboarding. Easy payments.', 'photo' => null, 'type' => 'about-us', 'created_at' => '2026-04-25 03:55:54', 'updated_at' => '2026-04-25 03:55:54', 'locale_id' => 13, 'locale' => 'en'],
            ['id' => 14, 'theme' => 'default', 'icon' => null, 'title' => 'Security', 'description' => 'Bank-level protection for every transaction.', 'photo' => null, 'type' => 'about-us', 'created_at' => '2026-04-25 03:55:54', 'updated_at' => '2026-04-25 03:55:54', 'locale_id' => 14, 'locale' => 'en'],
            ['id' => 15, 'theme' => 'default', 'icon' => null, 'title' => 'Inclusion', 'description' => 'Designed for all shoppers.', 'photo' => null, 'type' => 'about-us', 'created_at' => '2026-04-25 03:55:54', 'updated_at' => '2026-04-25 03:55:54', 'locale_id' => 15, 'locale' => 'en'],
            ['id' => 16, 'theme' => 'default', 'icon' => null, 'title' => 'What is Buy Now, Pay Later (BNPL)?', 'description' => 'BNPL allows you to purchase items today and split the total cost into smaller, scheduled payments - often interest-free.', 'photo' => null, 'type' => 'faq', 'created_at' => '2026-04-25 03:55:54', 'updated_at' => '2026-04-25 03:55:54', 'locale_id' => 16, 'locale' => 'en'],
            ['id' => 17, 'theme' => 'default', 'icon' => null, 'title' => 'Does it affect my credit score?', 'description' => 'No credit score impact during approval. Terms may vary depending on your final checkout flow.', 'photo' => null, 'type' => 'faq', 'created_at' => '2026-04-25 03:55:54', 'updated_at' => '2026-04-25 03:55:54', 'locale_id' => 17, 'locale' => 'en'],
            ['id' => 18, 'theme' => 'default', 'icon' => null, 'title' => 'How does the payment schedule work?', 'description' => 'Your purchase is divided into equal installments or monthly payments, depending on the plan you select.', 'photo' => null, 'type' => 'faq', 'created_at' => '2026-04-25 03:55:54', 'updated_at' => '2026-04-25 03:55:54', 'locale_id' => 18, 'locale' => 'en'],
            ['id' => 19, 'theme' => 'default', 'icon' => null, 'title' => 'Are there any hidden fees?', 'description' => 'No. What you see is what you pay.', 'photo' => null, 'type' => 'faq', 'created_at' => '2026-04-25 03:55:54', 'updated_at' => '2026-04-25 03:55:54', 'locale_id' => 19, 'locale' => 'en'],
            ['id' => 20, 'theme' => 'default', 'icon' => null, 'title' => 'What happens if I miss a payment?', 'description' => 'You will be notified before the due date. Late handling depends on your payment terms and account status.', 'photo' => null, 'type' => 'faq', 'created_at' => '2026-04-25 03:55:54', 'updated_at' => '2026-04-25 03:55:54', 'locale_id' => 20, 'locale' => 'en'],
            ['id' => 21, 'theme' => 'default', 'icon' => 'assets/landing-page/how-its-works/step-1.svg', 'title' => 'Choose BNPL at Checkout', 'description' => 'Select Pay with FlexPay when shopping.', 'photo' => null, 'type' => 'how-it-works', 'created_at' => '2026-04-25 03:55:54', 'updated_at' => '2026-04-25 03:55:54', 'locale_id' => 1, 'locale' => 'ar'],
            ['id' => 22, 'theme' => 'default', 'icon' => 'assets/landing-page/how-its-works/step-2.svg', 'title' => 'Get Instant Approval', 'description' => 'No credit score impact. Approval in seconds.', 'photo' => null, 'type' => 'how-it-works', 'created_at' => '2026-04-25 03:55:54', 'updated_at' => '2026-04-25 03:55:54', 'locale_id' => 2, 'locale' => 'ar'],
            ['id' => 23, 'theme' => 'default', 'icon' => 'assets/landing-page/how-its-works/step-3.svg', 'title' => 'Pay in Installments', 'description' => 'Split into 4 or monthly payments - interest free.', 'photo' => null, 'type' => 'how-it-works', 'created_at' => '2026-04-25 03:55:54', 'updated_at' => '2026-04-25 03:55:54', 'locale_id' => 3, 'locale' => 'ar'],
            ['id' => 24, 'theme' => 'default', 'icon' => 'assets/landing-page/stats/stats-1.png', 'title' => '$25M+', 'description' => 'Transactions Processed', 'photo' => null, 'type' => 'stats', 'created_at' => '2026-04-25 03:55:54', 'updated_at' => '2026-04-25 03:55:54', 'locale_id' => 4, 'locale' => 'ar'],
            ['id' => 25, 'theme' => 'default', 'icon' => 'assets/landing-page/stats/stats-2.png', 'title' => '50,000+', 'description' => 'Active Shoppers', 'photo' => null, 'type' => 'stats', 'created_at' => '2026-04-25 03:55:54', 'updated_at' => '2026-04-25 03:55:54', 'locale_id' => 5, 'locale' => 'ar'],
            ['id' => 26, 'theme' => 'default', 'icon' => 'assets/landing-page/stats/stats-3.png', 'title' => '1200+', 'description' => 'Partner Stores', 'photo' => null, 'type' => 'stats', 'created_at' => '2026-04-25 03:55:54', 'updated_at' => '2026-04-25 03:55:54', 'locale_id' => 6, 'locale' => 'ar'],
            ['id' => 27, 'theme' => 'default', 'icon' => 'assets/landing-page/stats/stats-4.png', 'title' => '98%', 'description' => 'Approval Rate', 'photo' => null, 'type' => 'stats', 'created_at' => '2026-04-25 03:55:54', 'updated_at' => '2026-04-25 03:55:54', 'locale_id' => 7, 'locale' => 'ar'],
            ['id' => 28, 'theme' => 'default', 'icon' => 'assets/landing-page/why-choose-us/why-choose-us-1.svg', 'title' => 'Instant Approval', 'description' => 'No paperwork. No waiting.', 'photo' => null, 'type' => 'why-choose-us', 'created_at' => '2026-04-25 03:55:54', 'updated_at' => '2026-04-25 03:55:54', 'locale_id' => 8, 'locale' => 'ar'],
            ['id' => 29, 'theme' => 'default', 'icon' => 'assets/landing-page/why-choose-us/why-choose-us-2.svg', 'title' => 'Bank-Level Security', 'description' => 'Your data is fully encrypted.', 'photo' => null, 'type' => 'why-choose-us', 'created_at' => '2026-04-25 03:55:54', 'updated_at' => '2026-04-25 03:55:54', 'locale_id' => 9, 'locale' => 'ar'],
            ['id' => 30, 'theme' => 'default', 'icon' => 'assets/landing-page/why-choose-us/why-choose-us-3.svg', 'title' => 'Zero Hidden Fees', 'description' => 'What you see is what you pay.', 'photo' => null, 'type' => 'why-choose-us', 'created_at' => '2026-04-25 03:55:54', 'updated_at' => '2026-04-25 03:55:54', 'locale_id' => 10, 'locale' => 'ar'],
            ['id' => 31, 'theme' => 'default', 'icon' => 'assets/landing-page/why-choose-us/why-choose-us-4.svg', 'title' => 'Manage in One App', 'description' => 'Track payments anytime.', 'photo' => null, 'type' => 'why-choose-us', 'created_at' => '2026-04-25 03:55:54', 'updated_at' => '2026-04-25 03:55:54', 'locale_id' => 11, 'locale' => 'ar'],
            ['id' => 32, 'theme' => 'default', 'icon' => null, 'title' => 'Transparency', 'description' => 'No hidden charges. Ever.', 'photo' => null, 'type' => 'about-us', 'created_at' => '2026-04-25 03:55:54', 'updated_at' => '2026-04-25 03:55:54', 'locale_id' => 12, 'locale' => 'ar'],
            ['id' => 33, 'theme' => 'default', 'icon' => null, 'title' => 'Simplicity', 'description' => 'Fast onboarding. Easy payments.', 'photo' => null, 'type' => 'about-us', 'created_at' => '2026-04-25 03:55:54', 'updated_at' => '2026-04-25 03:55:54', 'locale_id' => 13, 'locale' => 'ar'],
            ['id' => 34, 'theme' => 'default', 'icon' => null, 'title' => 'Security', 'description' => 'Bank-level protection for every transaction.', 'photo' => null, 'type' => 'about-us', 'created_at' => '2026-04-25 03:55:54', 'updated_at' => '2026-04-25 03:55:54', 'locale_id' => 14, 'locale' => 'ar'],
            ['id' => 35, 'theme' => 'default', 'icon' => null, 'title' => 'Inclusion', 'description' => 'Designed for all shoppers.', 'photo' => null, 'type' => 'about-us', 'created_at' => '2026-04-25 03:55:54', 'updated_at' => '2026-04-25 03:55:54', 'locale_id' => 15, 'locale' => 'ar'],
            ['id' => 36, 'theme' => 'default', 'icon' => null, 'title' => 'What is Buy Now, Pay Later (BNPL)?', 'description' => 'BNPL allows you to purchase items today and split the total cost into smaller, scheduled payments - often interest-free.', 'photo' => null, 'type' => 'faq', 'created_at' => '2026-04-25 03:55:54', 'updated_at' => '2026-04-25 03:55:54', 'locale_id' => 16, 'locale' => 'ar'],
            ['id' => 37, 'theme' => 'default', 'icon' => null, 'title' => 'Does it affect my credit score?', 'description' => 'No credit score impact during approval. Terms may vary depending on your final checkout flow.', 'photo' => null, 'type' => 'faq', 'created_at' => '2026-04-25 03:55:54', 'updated_at' => '2026-04-25 03:55:54', 'locale_id' => 17, 'locale' => 'ar'],
            ['id' => 38, 'theme' => 'default', 'icon' => null, 'title' => 'How does the payment schedule work?', 'description' => 'Your purchase is divided into equal installments or monthly payments, depending on the plan you select.', 'photo' => null, 'type' => 'faq', 'created_at' => '2026-04-25 03:55:54', 'updated_at' => '2026-04-25 03:55:54', 'locale_id' => 18, 'locale' => 'ar'],
            ['id' => 39, 'theme' => 'default', 'icon' => null, 'title' => 'Are there any hidden fees?', 'description' => 'No. What you see is what you pay.', 'photo' => null, 'type' => 'faq', 'created_at' => '2026-04-25 03:55:54', 'updated_at' => '2026-04-25 03:55:54', 'locale_id' => 19, 'locale' => 'ar'],
            ['id' => 40, 'theme' => 'default', 'icon' => null, 'title' => 'What happens if I miss a payment?', 'description' => 'You will be notified before the due date. Late handling depends on your payment terms and account status.', 'photo' => null, 'type' => 'faq', 'created_at' => '2026-04-25 03:55:54', 'updated_at' => '2026-04-25 03:55:54', 'locale_id' => 20, 'locale' => 'ar'],
        ];

        foreach ($records as $record) {
            DB::table('landing_contents')->updateOrInsert(
                ['id' => $record['id']],
                $record
            );
        }
    }
}
